### ISSUE TITLE
App crashes on ColorOS 11

### ISSUE THREAD

**Issue by VillagerTom** [HappyMax0/FCMPushViewer#3]
App crashes on start.

```
FATAL EXCEPTION: main
Process: com.happymax.fcmpushviewer, PID: 22850
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.happymax.fcmpushviewer/com.happymax.fcmpushviewer.MainActivity}: android.view.InflateException: Binary XML file line #13 in com.happymax.fcmpushviewer:layout/activity_main: Binary XML file line #13 in com.happymax.fcmpushviewer:layout/activity_main: Error inflating class com.google.android.material.appbar.AppBarLayout
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3719)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3886)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:140)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:100)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2316)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:263)
	at android.app.ActivityThread.main(ActivityThread.java:8288)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
Caused by: android.view.InflateException: Binary XML file line #13 in com.happymax.fcmpushviewer:layout/activity_main: Binary XML file line #13 in com.happymax.fcmpushviewer:layout/activity_main: Error inflating class com.google.android.material.appbar.AppBarLayout
Caused by: android.view.InflateException: Binary XML file line #13 in com.happymax.fcmpushviewer:layout/activity_main: Error inflating class com.google.android.material.appbar.AppBarLayout
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:852)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:775)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:197)
	at com.happymax.fcmpushviewer.MainActivity.onCreate(MainActivity.kt:49)
	at android.app.Activity.performCreate(Activity.java:8146)
	at android.app.Activity.performCreate(Activity.java:8130)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3688)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3886)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:140)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:100)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2316)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:263)
	at android.app.ActivityThread.main(ActivityThread.java:8288)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
Caused by: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.AppCompat (or a descendant).
	at com.google.android.material.internal.ThemeEnforcement.checkTheme(ThemeEnforcement.java:247)
	at com.google.android.material.internal.ThemeEnforcement.checkAppCompatTheme(ThemeEnforcement.java:212)
	at com.google.android.material.internal.ThemeEnforcement.checkCompatibleTheme(ThemeEnforcement.java:147)
	at com.google.android.material.internal.ThemeEnforcement.obtainStyledAttributes(ThemeEnforcement.java:76)
	at com.google.android.material.appbar.ViewUtilsLollipop.setStateListAnimatorFromAttrs(ViewUtilsLollipop.java:46)
	at com.google.android.material.appbar.AppBarLayout.<init>(AppBarLayout.java:247)
	at com.google.android.material.appbar.AppBarLayout.<init>(AppBarLayout.java:229)
	... 28 more
```

**Comment by HappyMax0** [comment]
May fixed on [2.2.1](https://github.com/HappyMax0/FCMPushViewer/releases/tag/2.2.1)

**Comment by HappyMax0** [comment]
May fixed on new release
Release 2.2.1 ・ HappyMax0/FCMPushViewer (github.com)<https://github.com/HappyMax0/FCMPushViewer/releases/tag/2.2.1>
________________________________
发件人: VillagerTom ***@***.***>
发送时间: 2024年9月6日 21:05
收件人: HappyMax0/FCMPushViewer ***@***.***>
抄送: Subscribed ***@***.***>
主题: [HappyMax0/FCMPushViewer] App crashes on ColorOS 11 (Issue #3)


App crashes on start.

FATAL EXCEPTION: main
Process: com.happymax.fcmpushviewer, PID: 22850
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.happymax.fcmpushviewer/com.happymax.fcmpushviewer.MainActivity}: android.view.InflateException: Binary XML file line #13 in com.happymax.fcmpushviewer:layout/activity_main: Binary XML file line #13 in com.happymax.fcmpushviewer:layout/activity_main: Error inflating class com.google.android.material.appbar.AppBarLayout
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3719)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3886)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:140)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:100)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2316)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:263)
        at android.app.ActivityThread.main(ActivityThread.java:8288)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
Caused by: android.view.InflateException: Binary XML file line #13 in com.happymax.fcmpushviewer:layout/activity_main: Binary XML file line #13 in com.happymax.fcmpushviewer:layout/activity_main: Error inflating class com.google.android.material.appbar.AppBarLayout
Caused by: android.view.InflateException: Binary XML file line #13 in com.happymax.fcmpushviewer:layout/activity_main: Error inflating class com.google.android.material.appbar.AppBarLayout
Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:852)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:775)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:197)
        at com.happymax.fcmpushviewer.MainActivity.onCreate(MainActivity.kt:49)
        at android.app.Activity.performCreate(Activity.java:8146)
        at android.app.Activity.performCreate(Activity.java:8130)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3688)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3886)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:140)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:100)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2316)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:263)
        at android.app.ActivityThread.main(ActivityThread.java:8288)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
Caused by: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.AppCompat (or a descendant).
        at com.google.android.material.internal.ThemeEnforcement.checkTheme(ThemeEnforcement.java:247)
        at com.google.android.material.internal.ThemeEnforcement.checkAppCompatTheme(ThemeEnforcement.java:212)
        at com.google.android.material.internal.ThemeEnforcement.checkCompatibleTheme(ThemeEnforcement.java:147)
        at com.google.android.material.internal.ThemeEnforcement.obtainStyledAttributes(ThemeEnforcement.java:76)
        at com.google.android.material.appbar.ViewUtilsLollipop.setStateListAnimatorFromAttrs(ViewUtilsLollipop.java:46)
        at com.google.android.material.appbar.AppBarLayout.<init>(AppBarLayout.java:247)
        at com.google.android.material.appbar.AppBarLayout.<init>(AppBarLayout.java:229)
        ... 28 more


―

**Comment by VillagerTom** [comment]
Crash has been fixed. Thanks!
